swagger: "2.0"
info:
  version: 1.0.0
  title: Sample API
  description: Sample of Swagger & API Gateway
basePath: /Prod
tags:
  - name: Version
schemes:
  - https
paths:
  /version:
    get:
      tags:
        - Version
      summary: PythonのVersion取得
      description: Lambdaで動作するPythonのVersionを取得する
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/Version"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PythonVersionFunction.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
      security:
        - SampleApiKey: []

securityDefinitions:
  SampleApiKey:
    type: apiKey
    name: x-api-key
    in: header

definitions:
  Version:
    type: object
    required:
      - python
    properties:
      python:
        type: string
