AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: sam-swagger-sample-api

Globals:
  Function:
    Timeout: 3

Resources:
  PythonVersionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://iam326.sam-swagger-sample/swagger.yaml

  SampleApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - PythonVersionApi
      - PythonVersionApiProdStage
    Properties:
      Name: sample-api-key
      Enabled: true
      StageKeys:
        - RestApiId: !Ref PythonVersionApi
          StageName: Prod

  SampleApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - PythonVersionApi
      - PythonVersionApiProdStage
    Properties:
      ApiStages:
        - ApiId: !Ref PythonVersionApi
          Stage: Prod
      Throttle:
        BurstLimit: 200
        RateLimit: 100
      UsagePlanName: sample-api-usage-plan

  SampleApiUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn:
      - SampleApiKey
      - SampleApiUsagePlan
    Properties:
      KeyId: !Ref SampleApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref SampleApiUsagePlan

  PythonVersionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        GetVersion:
          Type: Api
          Properties:
            Path: /version
            Method: get
            RestApiId: !Ref PythonVersionApi

Outputs:
  PythonVersionApiUrl:
    Description: API Gateway endpoint URL for Prod stage for Python Version Function
    Value: !Sub https://${PythonVersionApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/version
  SampleApiKey:
    Value: !Ref SampleApiKey
