name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          version: '3.7'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install pytest pytest-mock --user
      - name: Run API Test
        run: |
          pwd
          ls
          python --version
          pip --version
          ./python_test.sh
